
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s23/proj-happycows-s23-6pm-1
owner: ucsb-cs156-s23
repo_name: proj-happycows-s23-6pm-1
pull_requests: [{"author":{"id":"U_kgDOBX6DSQ","is_bot":false,"login":"mfletcher2","name":"Max Fletcher"},"headRefName":"max-newprofilepage","number":27,"title":"Display user information in table on profile page","url":"https://github.com/ucsb-cs156-s23/proj-happycows-s23-6pm-1/pull/27"},{"author":{"id":"MDQ6VXNlcjI0MjM3MDY1","is_bot":false,"login":"GlassBricks","name":"Benjamin Ye"},"headRefName":"ben-backend-use-health-update-strategies","number":23,"title":"Use different cow health update strategies in backend","url":"https://github.com/ucsb-cs156-s23/proj-happycows-s23-6pm-1/pull/23"}]
