
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s23/proj-happycows-s23-6pm-1
owner: ucsb-cs156-s23
repo_name: proj-happycows-s23-6pm-1
pull_requests: [{"author":{"id":"U_kgDOBX6DSQ","is_bot":false,"login":"mfletcher2","name":"Max Fletcher"},"headRefName":"max-commons_ui","number":47,"title":"Redesign play page UI","url":"https://github.com/ucsb-cs156-s23/proj-happycows-s23-6pm-1/pull/47"},{"author":{"id":"MDQ6VXNlcjI0MjM3MDY1","is_bot":false,"login":"GlassBricks","name":"Benjamin Ye"},"headRefName":"ben-refactor-UserCommons-table","number":46,"title":"Refactor UserCommons table to use a better table definition","url":"https://github.com/ucsb-cs156-s23/proj-happycows-s23-6pm-1/pull/46"},{"author":{"id":"MDQ6VXNlcjc3MDc2Mjc2","is_bot":false,"login":"JoeIsNoJoe","name":"Joe Z."},"headRefName":"Joe-FEATURE_Total_CowsBoughtSoldDeath","number":44,"title":"jz - Added feature that tracks total cows bought, sold, and died","url":"https://github.com/ucsb-cs156-s23/proj-happycows-s23-6pm-1/pull/44"},{"author":{"id":"U_kgDOBX6DSQ","is_bot":false,"login":"mfletcher2","name":"Max Fletcher"},"headRefName":"max-commonsCounter","number":38,"title":"Show number of days and players on Commons Overview","url":"https://github.com/ucsb-cs156-s23/proj-happycows-s23-6pm-1/pull/38"},{"author":{"id":"MDQ6VXNlcjI0MjM3MDY1","is_bot":false,"login":"GlassBricks","name":"Benjamin Ye"},"headRefName":"ben-frontend-cow-health-update-strategies","number":32,"title":"Use cow health update strategies in frontend","url":"https://github.com/ucsb-cs156-s23/proj-happycows-s23-6pm-1/pull/32"},{"author":{"id":"U_kgDOBtOWYg","is_bot":false,"login":"awgranados","name":""},"headRefName":"alex-add-current-milk-price","number":29,"title":"ag - added current milk price to user frontend","url":"https://github.com/ucsb-cs156-s23/proj-happycows-s23-6pm-1/pull/29"}]
